- type: job
  id: Militia
  name: job-name-militia
  description: job-description-militia
  playTimeTracker: JobMilitia
  startingGear: PassengerGear
  icon: "JobIconMilitia"
  setPreference: false
  overrideConsoleVisibility: true
  supervisors: job-supervisors-security
  access:
  - Command
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
