using System.IO;
using System.Linq;
using System.Numerics;
using Content.Client.Humanoid;
using Content.Client.Lobby.UI.Loadouts;
using Content.Client.Lobby.UI.Roles;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Stylesheets;
using Content.Client.Sprite;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.CCVar;
using Content.Shared.Clothing;
using Content.Shared.GameTicking;
using Content.Shared.Guidebook;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Direction = Robust.Shared.Maths.Direction;
using Robust.Shared.Physics.Systems;
using Robust.Shared.Physics;
using Content.Shared._DV.Traits;
using Content.Shared.Sprite; // DV - Traits

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly IResourceManager _resManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly LobbyUIController _controller;

        private readonly SpriteSystem _sprite;

        private readonly SharedScaleVisualsSystem _sharedScaleVisualsSystem;

        // CCvar.
        private int _maxNameLength;
        private int _maxCustomSpeciesLength; // Erida
        private bool _allowFlavorText;

        private FlavorText.FlavorText? _flavorText;
        private TextEdit? _flavorTextEdit;
        // Erida-Start
        private TextEdit? _flavorTextOOCEdit;
        private TextEdit? _characterTextEdit;
        private TextEdit? _greenTextEdit;
        private TextEdit? _yellowTextEdit;
        private TextEdit? _redTextEdit;
        private TextEdit? _tagsTextEdit;
        private TextEdit? _linksTextEdit;
        private TextEdit? _nsfwTextEdit;
        // Erida-End
        // Erida start
        private TextEdit? _nsfwLinksTextEdit;
        private TextEdit? _flavorTextNSFWOOCEdit;
        private TextEdit? _nsfwTagsTextEdit;
        // Erida end

        // One at a time.
        private LoadoutWindow? _loadoutWindow;

        private bool _exporting;
        private bool _imaging;

        /// <summary>
        /// If we're attempting to save.
        /// </summary>
        public event Action? Save;

        /// <summary>
        /// Temporary override of their selected job, used to preview roles.
        /// </summary>
        public JobPrototype? JobOverride;

        /// <summary>
        /// The character slot for the current profile.
        /// </summary>
        public int? CharacterSlot;

        /// <summary>
        /// The work in progress profile being edited.
        /// </summary>
        public HumanoidCharacterProfile? Profile;

        private List<SpeciesPrototype> _species = new();

        private List<(string, RequirementsSelector)> _jobPriorities = new();

        private readonly Dictionary<string, BoxContainer> _jobCategories;

        private Direction _previewRotation = Direction.North;

        private ColorSelectorSliders _rgbSkinColorSelector;

        private bool _isDirty;

        private static readonly ProtoId<GuideEntryPrototype> DefaultSpeciesGuidebook = "Species";

        public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;

        private ISawmill _sawmill;

        private MarkingsViewModel _markingsModel = new();

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings)
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            _resManager = resManager;
            _requirements = requirements;
            _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _sprite = _entManager.System<SpriteSystem>();
            _sharedScaleVisualsSystem = _entManager.System<SharedScaleVisualsSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _maxCustomSpeciesLength = _cfgManager.GetCVar(CCVars.MaxCustomSpeciesLength); // Erida
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);

            Markings.SetModel(_markingsModel);

            ImportButton.OnPressed += args =>
            {
                ImportProfile();
            };

            ExportButton.OnPressed += args =>
            {
                ExportProfile();
            };

            ExportImageButton.OnPressed += args =>
            {
                ExportImage();
            };

            OpenImagesButton.OnPressed += args =>
            {
                _resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            };

            ResetButton.OnPressed += args =>
            {
                SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            };

            SaveButton.OnPressed += args =>
            {
                Save?.Invoke();
            };

            Traits.OnTraitsChanged += OnTraitsSelectionChanged; // DeltaV

            #region Left

            #region Name

            NameEdit.OnTextChanged += args => { SetName(args.Text); };
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += args => RandomizeName();
            RandomizeEverythingButton.OnPressed += args => { RandomizeEverything(); };
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            #endregion Name

            #region Appearance

            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));

            #region Sex

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex)args.Id);
            };

            #endregion Sex

            #region Age

            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;

                SetAge(newAge);
            };

            #endregion Age

            #region Gender

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender)args.Id);
            };

            #endregion Gender

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                OnSkinColorOnValueChanged();
                // Erida start
                _markingsModel.Markings = [];
                UpdateMarkings();
                // Erida end
                UpdateHeightWidthSliders(); // Goobstation: port EE height/width sliders
            };

            // Erida-start
            IsCustomSpecies.OnPressed += _ =>
            {
                CustomSpeciesContainer.Visible = !CustomSpeciesContainer.Visible;
                if (!IsCustomSpecies.Pressed)
                    SetCustomSpecies(string.Empty);
            };

            CustomSpeciesEdit.IsValid = args => args.Length <= _maxCustomSpeciesLength;
            CustomSpeciesEdit.OnTextChanged += args =>
            {
                string formattedMessage = FormattedMessage.RemoveMarkupPermissive(args.Text);
                if (!string.IsNullOrEmpty(formattedMessage))
                    SetCustomSpecies(formattedMessage);
            };
            // Erida end

            // begin Goobstation: port EE height/width sliders
            #region Height and Width

            UpdateHeightWidthSliders();
            UpdateDimensions(SliderUpdate.Both);

            HeightSlider.OnValueChanged += _ => UpdateDimensions(SliderUpdate.Height);
            WidthSlider.OnValueChanged += _ => UpdateDimensions(SliderUpdate.Width);

            HeightReset.OnPressed += _ =>
            {
                var prototype = _species.Find(x => x.ID == Profile?.Species) ?? _species.First();
                HeightSlider.Value = prototype.DefaultHeight;
                UpdateDimensions(SliderUpdate.Height);
            };

            WidthReset.OnPressed += _ =>
            {
                var prototype = _species.Find(x => x.ID == Profile?.Species) ?? _species.First();
                WidthSlider.Value = prototype.DefaultWidth;
                UpdateDimensions(SliderUpdate.Width);
            };

            #endregion Height and Width
            // end Goobstation: port EE height/width sliders

            #region Skin

            Skin.OnValueChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            _rgbSkinColorSelector.OnColorChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            #endregion

            #region SpawnPriority

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int)value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference)args.Id);
            };

            #endregion SpawnPriority

            // Corvax-TTS-Start
            #region Voice

            if (configurationManager.GetCVar(CCVars.TTSEnabled))
            {
                TTSContainer.Visible = true;
                InitializeVoice();
            }

            #endregion
            // Corvax-TTS-End

            #region Citizenship

            RefreshCitizenships();

            CitizenshipButton.OnItemSelected += args =>
            {
                CitizenshipButton.SelectId(args.Id);
                var citizenshipId = (string?) CitizenshipButton.GetItemMetadata(args.Id);
                SetCitizenship(citizenshipId ?? string.Empty);
                RefreshBirthPlaces();
            };

            BirthPlaceButton.OnItemSelected += args =>
            {
                BirthPlaceButton.SelectId(args.Id);
                var birthPlace = (string?) BirthPlaceButton.GetItemMetadata(args.Id);
                SetBirthPlace(birthPlace ?? string.Empty);
            };

            #endregion Citizenship

            #region Eyes

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeColor(newColor));
                _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor);
                ReloadProfilePreview();
            };

            #endregion Eyes

            #endregion Appearance

            #region Jobs

            TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-jobs-tab"));

            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-stay-in-lobby-button"),
                (int)PreferenceUnavailableMode.StayInLobby);
            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-spawn-as-overflow-button",
                              ("overflowJob", Loc.GetString(SharedGameTicker.FallbackOverflowJobName))),
                (int)PreferenceUnavailableMode.SpawnAsOverflow);

            PreferenceUnavailableButton.OnItemSelected += args =>
            {
                PreferenceUnavailableButton.SelectId(args.Id);
                Profile = Profile?.WithPreferenceUnavailable((PreferenceUnavailableMode)args.Id);
                SetDirty();
            };

            _jobCategories = new Dictionary<string, BoxContainer>();

            RefreshAntags();
            RefreshJobs();

            #endregion Jobs

            TabContainer.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-antags-tab"));

            // RefreshTraits(); // DeltaV

            #region Markings

            TabContainer.SetTabTitle(4, Loc.GetString("humanoid-profile-editor-markings-tab"));

            _markingsModel.MarkingsChanged += (_, _) => OnMarkingChange();
            _markingsModel.MarkingsReset += OnMarkingChange;

            #endregion Markings

            RefreshFlavorText();

            #region Dummy

            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };
            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };

            #endregion Dummy

            #endregion Left

            ShowClothes.OnToggled += args =>
            {
                ReloadPreview();
            };

            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            UpdateSpeciesGuidebookIcon();
            IsDirty = false;
        }

        // Begin DeltaV - Traits Integration
        /// <summary>
        /// Called when trait selection changes in the TraitsTab.
        /// Updates the profile with the new trait selection.
        /// </summary>
        private void OnTraitsSelectionChanged(HashSet<ProtoId<TraitPrototype>> traits)
        {
            if (Profile is null)
                return;

            // Remove all existing traits - iterate directly over readonly collection
            foreach (var existingTrait in Profile.TraitPreferences)
            {
                Profile = Profile.WithoutTraitPreference(existingTrait, _prototypeManager);
            }

            // Add newly selected traits
            foreach (var trait in traits)
            {
                Profile = Profile.WithTraitPreference(trait.Id, _prototypeManager);
            }

            SetDirty();
        }

        /// <summary>
        /// Updates the traits tab with the current profile's selected traits.
        /// </summary>
        private void UpdateTraitsSelection()
        {
            if (Profile is null)
            {
                Traits.SetSelectedTraits(new HashSet<ProtoId<TraitPrototype>>());
                return;
            }

            TabContainer.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-traits-tab"));

            // Convert profile's trait preferences (strings) to ProtoId<TraitPrototype>
            var selectedTraits = new HashSet<ProtoId<TraitPrototype>>(Profile.TraitPreferences.Count);
            foreach (var traitId in Profile.TraitPreferences)
            {
                // Validate that the trait still exists in prototypes
                if (_prototypeManager.HasIndex(traitId))
                {
                    selectedTraits.Add(new ProtoId<TraitPrototype>(traitId));
                }
            }

            Traits.SetSelectedTraits(selectedTraits);
            Traits.UpdateConditions(Profile.Species);
        }
        // End DeltaV - Traits Integration

        /// <summary>
        /// Refreshes the flavor text editor status.
        /// </summary>
        public void RefreshFlavorText()
        {
            if (_allowFlavorText)
            {
                if (_flavorText != null)
                    return;

                _flavorText = new FlavorText.FlavorText();
                TabContainer.AddChild(_flavorText);
                TabContainer.SetTabTitle(TabContainer.ChildCount - 1, Loc.GetString("humanoid-profile-editor-flavortext-tab"));

                _flavorTextEdit = _flavorText.CFlavorTextInput;
                // Erida start
                _flavorTextNSFWOOCEdit = _flavorText.CFlavorNSFWOOCTextInput;
                _nsfwLinksTextEdit = _flavorText.CNSFWLinksTextInput;
                _nsfwTagsTextEdit = _flavorText.CNSFWTagsTextInput;
                // Erida end
                // Erida-Start
                _flavorTextOOCEdit = _flavorText.CFlavorOOCTextInput;
                _characterTextEdit = _flavorText.CCharacterTextInput;
                _greenTextEdit = _flavorText.CGreenTextInput;
                _yellowTextEdit = _flavorText.CYellowTextInput;
                _redTextEdit = _flavorText.CRedTextInput;
                _tagsTextEdit = _flavorText.CTagsTextInput;
                _linksTextEdit = _flavorText.CLinksTextInput;
                _nsfwTextEdit = _flavorText.CNSFWTextInput;

                // Erida-End

                _flavorText.OnFlavorTextChanged += OnFlavorTextChange;
                // Erida-Start
                _flavorText.OnFlavorOOCTextChanged += OnFlavorOOCTextChange;
                _flavorText.OnCharacterTextChanged += OnCharacterFlavorTextChange;
                _flavorText.OnGreenTextChanged += OnGreenFlavorTextChange;
                _flavorText.OnYellowTextChanged += OnYellowFlavorTextChange;
                _flavorText.OnRedTextChanged += OnRedFlavorTextChange;
                _flavorText.OnTagsTextChanged += OnTagsFlavorTextChange;
                _flavorText.OnLinksTextChanged += OnLinksFlavorTextChange;
                _flavorText.OnNSFWTextChanged += OnNSFWFlavorTextChange;
                // Erida-End
                // Erida start
                _flavorText.OnNSFWLinksTextChanged += OnNSFWLinksFlavorTextChange;
                _flavorText.OnNSFWFlavorOOCTextChanged += OnFlavorNSFWOOCTextChange;
                _flavorText.OnNSFWTagsTextChanged += OnNSFWTagsFlavorTextChange;
                _flavorText.OnFlavorTabChanged += OnTabChanged;
                // Erida end
            }
            else
            {
                if (_flavorText == null)
                    return;

                _flavorText.OnFlavorTextChanged -= OnFlavorTextChange;
                // Erida-Start
                _flavorText.OnFlavorOOCTextChanged -= OnFlavorOOCTextChange;
                _flavorText.OnCharacterTextChanged -= OnCharacterFlavorTextChange;
                _flavorText.OnGreenTextChanged -= OnGreenFlavorTextChange;
                _flavorText.OnYellowTextChanged -= OnYellowFlavorTextChange;
                _flavorText.OnRedTextChanged -= OnRedFlavorTextChange;
                _flavorText.OnTagsTextChanged -= OnTagsFlavorTextChange;
                _flavorText.OnLinksTextChanged -= OnLinksFlavorTextChange;
                _flavorText.OnNSFWTextChanged -= OnNSFWFlavorTextChange;
                // Erida-End
                // Erida start
                _flavorText.OnNSFWLinksTextChanged -= OnNSFWLinksFlavorTextChange;
                _flavorText.OnNSFWFlavorOOCTextChanged -= OnFlavorNSFWOOCTextChange;
                _flavorText.OnNSFWTagsTextChanged -= OnNSFWTagsFlavorTextChange;
                _flavorText.OnFlavorTabChanged -= OnTabChanged;
                // Erida end

                TabContainer.RemoveChild(_flavorText);
                _flavorText.Dispose();
                _flavorTextEdit?.Dispose();

                _flavorTextEdit = null;
                // Erida-Start
                _flavorTextOOCEdit = null;
                _characterTextEdit = null;
                _greenTextEdit = null;
                _yellowTextEdit = null;
                _redTextEdit = null;
                _tagsTextEdit = null;
                _linksTextEdit = null;
                _nsfwTextEdit = null;
                // Erida-End
                // Erida start
                _nsfwLinksTextEdit = null;
                _flavorTextNSFWOOCEdit = null;
                _nsfwTagsTextEdit = null;
                // Erida end

                _flavorText = null;
            }
        }

        // Erida start
        private void UpdateNSFWPreviewVisibility(bool showNsfw)
        {
            if (_flavorText == null)
                return;
        }
        private void OnTabChanged(int tab)
        {
            switch (tab)
            {
                case 3:
                    UpdateNSFWPreviewVisibility(true);
                    break;
                default:
                    UpdateNSFWPreviewVisibility(false);
                    break;
            }
        }
        // Erida end

        // Erida-Start

        private void ProcessLinks(string linksText, BoxContainer linksContainer)
        {
            if (linksContainer == null)
                return;

            linksContainer.RemoveAllChildren();
            if (string.IsNullOrEmpty(linksText))
                return;

            var links = linksText.Split(new[] { ',', ' ', '\n', '\r', '\t' }, StringSplitOptions.RemoveEmptyEntries);
            foreach (var link in links)
            {
                if (IsValidUrl(link))
                {
                    CreateLinkButton(link, linksContainer); // Erida edit
                }
                else
                {
                    CreateLinkTextLabel(link, linksContainer); // Erida edit
                }
            }
        }

        private bool IsValidUrl(string url)
        {
            return url.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
                url.StartsWith("https://", StringComparison.OrdinalIgnoreCase) ||
                url.StartsWith("www.", StringComparison.OrdinalIgnoreCase);
        }

        private void CreateLinkButton(string url, BoxContainer linksContainer) // Erida edit
        {
            var button = new Button
            {
                Text = GetLinkDisplayText(url),
                ToolTip = Loc.GetString("humanoid-profile-editor-link-tooltip", ("url", url)),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                StyleClasses = { StyleNano.ButtonOpenBoth }
            };

            button.OnPressed += _ => OpenLink(url);

            linksContainer.AddChild(button); // Erida edit
        }

        private void CreateLinkTextLabel(string text, BoxContainer linksContainer) // Erida edit
        {
            var label = new Label
            {
                Text = text,
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                FontColorOverride = Color.Gray
            };

            linksContainer.AddChild(label); // Erida edit
        }

        private string GetLinkDisplayText(string url)
        {
            if (url.Length > 40)
            {
                return url[..37] + "...";
            }
            return url;
        }

        private void OpenLink(string url)
        {
            if (url.StartsWith("www.", StringComparison.OrdinalIgnoreCase))
                url = "https://" + url;

            var uriOpener = IoCManager.Resolve<IUriOpener>();
            uriOpener.OpenUri(url);
        }
        // Erida-End

        /// <summary>
        /// Refreshes traits selector
        /// </summary>
        // public void RefreshTraits()
        // {
        //     TraitsList.RemoveAllChildren();
        //
        //     var traits = _prototypeManager.EnumeratePrototypes<TraitPrototype>().OrderBy(t => Loc.GetString(t.Name)).ToList();
        //     TabContainer.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-traits-tab"));
        //
        //     if (traits.Count < 1)
        //     {
        //         TraitsList.AddChild(new Label
        //         {
        //             Text = Loc.GetString("humanoid-profile-editor-no-traits"),
        //             FontColorOverride = Color.Gray,
        //         });
        //         return;
        //     }
        //
        //     // Setup model
        //     Dictionary<string, List<string>> traitGroups = new();
        //     List<string> defaultTraits = new();
        //     traitGroups.Add(TraitCategoryPrototype.Default, defaultTraits);
        //
        //     foreach (var trait in traits)
        //     {
        //         // Begin DeltaV Additions - Species trait exclusion
        //         if (Profile?.Species is { } selectedSpecies && trait.ExcludedSpecies.Contains(selectedSpecies))
        //         {
        //             Profile = Profile?.WithoutTraitPreference(trait.ID, _prototypeManager);
        //             continue;
        //         }
        //         // End DeltaV Additions
        //
        //         if (trait.Category == null)
        //         {
        //             defaultTraits.Add(trait.ID);
        //             continue;
        //         }
        //
        //         if (!_prototypeManager.HasIndex(trait.Category))
        //             continue;
        //
        //         var group = traitGroups.GetOrNew(trait.Category);
        //         group.Add(trait.ID);
        //     }
        //
        //     // Create UI view from model
        //     foreach (var (categoryId, categoryTraits) in traitGroups)
        //     {
        //         TraitCategoryPrototype? category = null;
        //
        //         if (categoryId != TraitCategoryPrototype.Default)
        //         {
        //             category = _prototypeManager.Index<TraitCategoryPrototype>(categoryId);
        //             // Label
        //             TraitsList.AddChild(new Label
        //             {
        //                 Text = Loc.GetString(category.Name),
        //                 Margin = new Thickness(0, 10, 0, 0),
        //                 StyleClasses = { StyleClass.LabelHeading },
        //             });
        //         }
        //
        //         List<TraitPreferenceSelector?> selectors = new();
        //         var selectionCount = 0;
        //
        //         foreach (var traitProto in categoryTraits)
        //         {
        //             var trait = _prototypeManager.Index<TraitPrototype>(traitProto);
        //             var selector = new TraitPreferenceSelector(trait);
        //
        //             selector.Preference = Profile?.TraitPreferences.Contains(trait.ID) == true;
        //             if (selector.Preference)
        //                 selectionCount += trait.Cost;
        //
        //             selector.PreferenceChanged += preference =>
        //             {
        //                 if (preference)
        //                 {
        //                     Profile = Profile?.WithTraitPreference(trait.ID, _prototypeManager);
        //                 }
        //                 else
        //                 {
        //                     Profile = Profile?.WithoutTraitPreference(trait.ID, _prototypeManager);
        //                 }
        //
        //                 SetDirty();
        //                 RefreshTraits(); // If too many traits are selected, they will be reset to the real value.
        //             };
        //             selectors.Add(selector);
        //         }
        //
        //         // Selection counter
        //         if (category is { MaxTraitPoints: >= 0 })
        //         {
        //             TraitsList.AddChild(new Label
        //             {
        //                 Text = Loc.GetString("humanoid-profile-editor-trait-count-hint", ("current", selectionCount) ,("max", category.MaxTraitPoints)),
        //                 FontColorOverride = Color.Gray
        //             });
        //         }
        //
        //         foreach (var selector in selectors)
        //         {
        //             if (selector == null)
        //                 continue;
        //
        //             if (category is { MaxTraitPoints: >= 0 } &&
        //                 selector.Cost + selectionCount > category.MaxTraitPoints)
        //             {
        //                 selector.Checkbox.Label.FontColorOverride = Color.Red;
        //             }
        //
        //             TraitsList.AddChild(selector);
        //         }
        //     }
        // }

        /// <summary>
        /// Refreshes the species selector.
        /// </summary>
        public void RefreshSpecies()
        {
            SpeciesButton.Clear();
            _species.Clear();

            _species.AddRange(_prototypeManager.EnumeratePrototypes<SpeciesPrototype>().Where(o => o.RoundStart));
            _species.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.CurrentCultureIgnoreCase));
            var speciesIds = _species.Select(o => o.ID).ToList();

            for (var i = 0; i < _species.Count; i++)
            {
                var name = Loc.GetString(_species[i].Name);
                SpeciesButton.AddItem(name, i);

                if (Profile?.Species.Equals(_species[i].ID) == true)
                {
                    SpeciesButton.SelectId(i);
                }
            }

            // If our species isn't available then reset it to default.
            if (Profile != null)
            {
                if (!speciesIds.Contains(Profile.Species))
                {
                    SetSpecies(HumanoidCharacterProfile.DefaultSpecies);
                }
            }
        }

        public void RefreshAntags()
        {
            AntagList.RemoveAllChildren();
            var items = new[]
            {
                ("humanoid-profile-editor-antag-preference-yes-button", 0),
                ("humanoid-profile-editor-antag-preference-no-button", 1)
            };

            foreach (var antag in _prototypeManager.EnumeratePrototypes<AntagPrototype>().OrderBy(a => Loc.GetString(a.Name)))
            {
                if (!antag.SetPreference)
                    continue;

                var antagContainer = new BoxContainer()
                {
                    Orientation = LayoutOrientation.Horizontal,
                };

                var selector = new RequirementsSelector()
                {
                    Margin = new Thickness(3f, 3f, 3f, 0f),
                };
                selector.OnOpenGuidebook += OnOpenGuidebook;

                var title = Loc.GetString(antag.Name);
                var description = Loc.GetString(antag.Objective);
                selector.Setup(items, title, 250, description, guides: antag.Guides);
                selector.Select(Profile?.AntagPreferences.Contains(antag.ID) == true ? 0 : 1);

                if (!_requirements.IsAllowed(
                        antag,
                        (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                        out var reason))
                {
                    selector.LockRequirements(reason);
                    Profile = Profile?.WithAntagPreference(antag.ID, false);
                    SetDirty();
                }
                else
                {
                    selector.UnlockRequirements();
                }

                selector.OnSelected += preference =>
                {
                    Profile = Profile?.WithAntagPreference(antag.ID, preference == 0);
                    SetDirty();
                };

                antagContainer.AddChild(selector);

                antagContainer.AddChild(new Button()
                {
                    Disabled = true,
                    Text = Loc.GetString("loadout-window"),
                    HorizontalAlignment = HAlignment.Right,
                    Margin = new Thickness(3f, 0f, 0f, 0f),
                });

                AntagList.AddChild(antagContainer);
            }
        }

        private void SetDirty()
        {
            // If it equals default then reset the button.
            if (Profile == null || _preferencesManager.Preferences?.SelectedCharacter.MemberwiseEquals(Profile) == true)
            {
                IsDirty = false;
                return;
            }

            // TODO: Check if profile matches default.
            IsDirty = true;
        }

        /// <summary>
        /// Refresh all loadouts.
        /// </summary>
        public void RefreshLoadouts()
        {
            _loadoutWindow?.Dispose();
        }

        /// <summary>
        /// Reloads the entire dummy entity for preview.
        /// </summary>
        /// <remarks>
        /// This is expensive so not recommended to run if you have a slider.
        /// </remarks>
        private void ReloadPreview()
        {
            if (Profile == null)
                return;

            SpriteView.LoadPreview(Profile, JobOverride, ShowClothes.Pressed);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        /// <summary>
        /// Resets the profile to the defaults.
        /// </summary>
        public void ResetToDefault()
        {
            SetProfile(
                (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        /// <summary>
        /// Sets the editor to the specified profile with the specified slot.
        /// </summary>
        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            IsDirty = false;
            JobOverride = null;

            UpdateNameEdit();
            UpdateFlavorTextEdit();
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();
            UpdateTTSVoicesControls(); // Corvax-TTS
            UpdateCustomSpeciesEdit(); // Erida edit

            UpdateTraitsSelection(); // DeltaV - Traits

            RefreshAntags();
            RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            // RefreshTraits(); // DeltaV
            RefreshFlavorText();
            ReloadPreview();

            UpdateHeightWidthSliders(); // Goobstation: port EE height/width sliders
            UpdateWeight(); // Goobstation: port EE height/width sliders

            RefreshCitizenships();
            RefreshBirthPlaces();

            if (Profile != null)
            {
                PreferenceUnavailableButton.SelectId((int)Profile.PreferenceUnavailable);
            }

            // Reset dirty flag after all refreshes, since ReloadPreview() calls SetDirty().
            IsDirty = false;
        }

        /// <summary>
        /// A slim reload that only updates the entity itself and not any of the job entities, etc.
        /// </summary>
        private void ReloadProfilePreview()
        {
            if (Profile == null)
                return;

            SpriteView.ReloadProfilePreview(Profile);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        private void OnSpeciesInfoButtonPressed(BaseButton.ButtonEventArgs args)
        {
            // TODO GUIDEBOOK
            // make the species guide book a field on the species prototype.
            // I.e., do what jobs/antags do.

            var guidebookController = UserInterfaceManager.GetUIController<GuidebookUIController>();
            var species = Profile?.Species ?? HumanoidCharacterProfile.DefaultSpecies;
            var page = DefaultSpeciesGuidebook;
            if (_prototypeManager.HasIndex<GuideEntryPrototype>(species))
                page = new ProtoId<GuideEntryPrototype>(species.Id); // Gross. See above todo comment.

            if (_prototypeManager.Resolve(DefaultSpeciesGuidebook, out var guideRoot))
            {
                var dict = new Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry>();
                dict.Add(DefaultSpeciesGuidebook, guideRoot);
                //TODO: Don't close the guidebook if its already open, just go to the correct page
                guidebookController.OpenGuidebook(dict, includeChildren: true, selected: page);
            }
        }

        /// <summary>
        /// Refreshes all job selectors.
        /// </summary>
        public void RefreshJobs()
        {
            JobList.RemoveAllChildren();
            _jobCategories.Clear();
            _jobPriorities.Clear();
            var firstCategory = true;

            // Get all displayed departments
            var departments = new List<DepartmentPrototype>();
            foreach (var department in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
            {
                if (department.EditorHidden)
                    continue;

                departments.Add(department);
            }

            departments.Sort(DepartmentUIComparer.Instance);

            var items = new[]
            {
                ("humanoid-profile-editor-job-priority-never-button", (int) JobPriority.Never),
                ("humanoid-profile-editor-job-priority-low-button", (int) JobPriority.Low),
                ("humanoid-profile-editor-job-priority-medium-button", (int) JobPriority.Medium),
                ("humanoid-profile-editor-job-priority-high-button", (int) JobPriority.High),
            };

            foreach (var department in departments)
            {
                var departmentName = Loc.GetString(department.Name);

                if (!_jobCategories.TryGetValue(department.ID, out var category))
                {
                    category = new BoxContainer
                    {
                        Orientation = LayoutOrientation.Vertical,
                        Name = department.ID,
                        ToolTip = Loc.GetString("humanoid-profile-editor-jobs-amount-in-department-tooltip",
                            ("departmentName", departmentName))
                    };

                    if (firstCategory)
                    {
                        firstCategory = false;
                    }
                    else
                    {
                        category.AddChild(new Control
                        {
                            MinSize = new Vector2(0, 23),
                        });
                    }

                    category.AddChild(new PanelContainer
                    {
                        PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#464966") },
                        Children =
                        {
                            new Label
                            {
                                Text = Loc.GetString("humanoid-profile-editor-department-jobs-label",
                                    ("departmentName", departmentName)),
                                Margin = new Thickness(5f, 0, 0, 0)
                            }
                        }
                    });

                    _jobCategories[department.ID] = category;
                    JobList.AddChild(category);
                }

                var jobs = department.Roles.Select(jobId => _prototypeManager.Index(jobId))
                    .Where(job => job.SetPreference)
                    .ToArray();

                Array.Sort(jobs, JobUIComparer.Instance);

                foreach (var job in jobs)
                {
                    var jobContainer = new BoxContainer()
                    {
                        Orientation = LayoutOrientation.Horizontal,
                    };

                    var selector = new RequirementsSelector()
                    {
                        Margin = new Thickness(3f, 3f, 3f, 0f),
                    };
                    selector.OnOpenGuidebook += OnOpenGuidebook;

                    var icon = new TextureRect
                    {
                        TextureScale = new Vector2(2, 2),
                        VerticalAlignment = VAlignment.Center
                    };
                    var jobIcon = _prototypeManager.Index(job.Icon);
                    icon.Texture = _sprite.Frame0(jobIcon.Icon);
                    selector.Setup(items, job.LocalizedName, 200, job.LocalizedDescription, icon, job.Guides);

                    if (!_requirements.IsAllowed(job, (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, out var reason))
                    {
                        selector.LockRequirements(reason);
                    }
                    else
                    {
                        selector.UnlockRequirements();
                    }

                    selector.OnSelected += selectedPrio =>
                    {
                        var selectedJobPrio = (JobPriority)selectedPrio;
                        Profile = Profile?.WithJobPriority(job.ID, selectedJobPrio);

                        foreach (var (jobId, other) in _jobPriorities)
                        {
                            // Sync other selectors with the same job in case of multiple department jobs
                            if (jobId == job.ID)
                            {
                                other.Select(selectedPrio);
                                continue;
                            }

                            if (selectedJobPrio != JobPriority.High || (JobPriority)other.Selected != JobPriority.High)
                                continue;

                            // Lower any other high priorities to medium.
                            other.Select((int)JobPriority.Medium);
                            Profile = Profile?.WithJobPriority(jobId, JobPriority.Medium);
                        }

                        // TODO: Only reload on high change (either to or from).
                        ReloadPreview();

                        UpdateJobPriorities();
                        SetDirty();
                    };

                    var loadoutWindowBtn = new Button()
                    {
                        Text = Loc.GetString("loadout-window"),
                        HorizontalAlignment = HAlignment.Right,
                        VerticalAlignment = VAlignment.Center,
                        Margin = new Thickness(3f, 3f, 0f, 0f),
                    };

                    var collection = IoCManager.Instance!;
                    var protoManager = collection.Resolve<IPrototypeManager>();

                    // If no loadout found then disabled button
                    if (!protoManager.TryIndex<RoleLoadoutPrototype>(LoadoutSystem.GetJobPrototype(job.ID), out var roleLoadoutProto))
                    {
                        loadoutWindowBtn.Disabled = true;
                    }
                    // else
                    else
                    {
                        loadoutWindowBtn.OnPressed += args =>
                        {
                            RoleLoadout? loadout = null;

                            // Clone so we don't modify the underlying loadout.
                            Profile?.Loadouts.TryGetValue(LoadoutSystem.GetJobPrototype(job.ID), out loadout);
                            loadout = loadout?.Clone();

                            if (loadout == null)
                            {
                                loadout = new RoleLoadout(roleLoadoutProto.ID);
                                loadout.SetDefault(Profile, _playerManager.LocalSession, _prototypeManager);
                            }

                            OpenLoadout(job, loadout, roleLoadoutProto);
                        };
                    }

                    _jobPriorities.Add((job.ID, selector));
                    jobContainer.AddChild(selector);
                    jobContainer.AddChild(loadoutWindowBtn);
                    category.AddChild(jobContainer);
                }
            }

            UpdateJobPriorities();
        }

        private void OpenLoadout(JobPrototype? jobProto, RoleLoadout roleLoadout, RoleLoadoutPrototype roleLoadoutProto)
        {
            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
            var collection = IoCManager.Instance;

            if (collection == null || _playerManager.LocalSession == null || Profile == null)
                return;

            JobOverride = jobProto;
            var session = _playerManager.LocalSession;

            _loadoutWindow = new LoadoutWindow(Profile, roleLoadout, roleLoadoutProto, _playerManager.LocalSession, collection)
            {
                Title = Loc.GetString("loadout-window-title-loadout", ("job", $"{jobProto?.LocalizedName}")),
            };

            // Refresh the buttons etc.
            _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
            _loadoutWindow.OpenCenteredLeft();

            _loadoutWindow.OnNameChanged += name =>
            {
                roleLoadout.EntityName = name;
                Profile = Profile.WithLoadout(roleLoadout);
                SetDirty();
            };

            _loadoutWindow.OnLoadoutPressed += (loadoutGroup, loadoutProto) =>
            {
                roleLoadout.AddLoadout(loadoutGroup, loadoutProto, _prototypeManager);
                _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
                Profile = Profile?.WithLoadout(roleLoadout);
                ReloadPreview();
            };

            _loadoutWindow.OnLoadoutUnpressed += (loadoutGroup, loadoutProto) =>
            {
                roleLoadout.RemoveLoadout(loadoutGroup, loadoutProto, _prototypeManager);
                _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
                Profile = Profile?.WithLoadout(roleLoadout);
                ReloadPreview();
            };

            JobOverride = jobProto;
            ReloadPreview();

            _loadoutWindow.OnClose += () =>
            {
                JobOverride = null;
                ReloadPreview();
            };

            if (Profile is null)
                return;

            UpdateJobPriorities();
        }

        private void OnFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithFlavorText(content);
            SetDirty();
        }

        // Erida-Start
        private void OnFlavorOOCTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithOOCFlavorText(content);
            SetDirty();


        }

        private void OnCharacterFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithCharacterText(content);
            SetDirty();


        }

        private void OnGreenFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithGreenPreferencesText(content);
            SetDirty();


        }

        private void OnYellowFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithYellowPreferencesText(content);
            SetDirty();


        }

        private void OnRedFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithRedPreferencesText(content);
            SetDirty();


        }

        private void OnTagsFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithTagsText(content);
            SetDirty();


        }

        private void OnLinksFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithLinksText(content);
            SetDirty();


        }

        private void OnNSFWFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithNSFWPreferencesText(content);
            SetDirty();


        }
        // Erida-End
        // Erida start
        private void OnFlavorNSFWOOCTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithNSFWOOCFlavorText(content);
            SetDirty();


        }

        private void OnNSFWLinksFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithNSFWLinksText(content);
            SetDirty();


        }

        private void OnNSFWTagsFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithNSFWTagsText(content);
            SetDirty();


        }
        // Erida end

        private void OnMarkingChange()
        {
            if (Profile is null)
                return;

            Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithMarkings(_markingsModel.Markings));
            ReloadProfilePreview();
            SetDirty();
        }

        private void OnSkinColorOnValueChanged()
        {
            if (Profile is null) return;

            var skin = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
            var strategy = _prototypeManager.Index(skin).Strategy;

            switch (strategy.InputType)
            {
                case SkinColorationStrategyInput.Unary:
                    {
                        if (!Skin.Visible)
                        {
                            Skin.Visible = true;
                            RgbSkinColorContainer.Visible = false;
                        }

                        var color = strategy.FromUnary(Skin.Value);

                        _markingsModel.SetOrganSkinColor(color);
                        Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));

                        break;
                    }
                case SkinColorationStrategyInput.Color:
                    {
                        if (!RgbSkinColorContainer.Visible)
                        {
                            Skin.Visible = false;
                            RgbSkinColorContainer.Visible = true;
                        }

                        var color = strategy.ClosestSkinColor(_rgbSkinColorSelector.Color);

                        _markingsModel.SetOrganSkinColor(color);
                        Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));

                        break;
                    }
            }

            ReloadProfilePreview();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        private void SetAge(int newAge)
        {
            Profile = Profile?.WithAge(newAge);
            ReloadPreview();
        }

        private void SetSex(Sex newSex)
        {
            Profile = Profile?.WithSex(newSex);
            // for convenience, default to most common gender when new sex is selected
            switch (newSex)
            {
                case Sex.Male:
                    Profile = Profile?.WithGender(Gender.Male);
                    break;
                case Sex.Female:
                    Profile = Profile?.WithGender(Gender.Female);
                    break;
                default:
                    Profile = Profile?.WithGender(Gender.Epicene);
                    break;
            }

            UpdateTTSVoicesControls(); // Corvax-TTS
            UpdateGenderControls();
            _markingsModel.SetOrganSexes(newSex);
            ReloadPreview();
        }

        private void SetGender(Gender newGender)
        {
            Profile = Profile?.WithGender(newGender);
            ReloadPreview();
        }

        // Corvax-TTS-Start
        private void SetVoice(string newVoice)
        {
            Profile = Profile?.WithVoice(newVoice);
            IsDirty = true;
        }
        // Corvax-TTS-End

        private void SetSpecies(string newSpecies)
        {
            Profile = Profile?.WithSpecies(newSpecies);
            OnSkinColorOnValueChanged(); // Species may have special color prefs, make sure to update it.
            _markingsModel.OrganData = _markingManager.GetMarkingData(newSpecies);
            _markingsModel.ValidateMarkings();
            // In case there's job restrictions for the species
            RefreshJobs();
            // In case there's species restrictions for loadouts
            RefreshLoadouts();
            UpdateSexControls(); // update sex for new species
            UpdateSpeciesGuidebookIcon();
            ReloadPreview();
        }


        // Erida-start
        private void SetCustomSpecies(string newSpecies)
        {
            Profile = Profile?.WithCustomSpecies(newSpecies);
            IsDirty = true;
        }
        // Erida-end

        private void SetName(string newName)
        {
            Profile = Profile?.WithName(newName);
            SetDirty();

            if (!IsDirty)
                return;

            SpriteView.SetName(newName);
        }

        private void SetSpawnPriority(SpawnPriorityPreference newSpawnPriority)
        {
            Profile = Profile?.WithSpawnPriorityPreference(newSpawnPriority);
            SetDirty();
        }

        // Goob Station - Start
        private void SetProfileHeight(float height)
        {
            Profile = Profile?.WithHeight(height);
            ReloadProfilePreview();
            IsDirty = true;
        }

        private void SetProfileWidth(float width)
        {
            Profile = Profile?.WithWidth(width);
            ReloadProfilePreview();
            IsDirty = true;
        }
        // Goob Station - End

        private void SetCitizenship(string citizenship)
        {
            Profile = Profile?.WithCitizenship(citizenship);
            SetDirty();
        }

        private void SetBirthPlace(string birthPlace)
        {
            Profile = Profile?.WithBirthPlace(birthPlace);
            SetDirty();
        }

        private void RefreshCitizenships()
        {
            CitizenshipButton.Clear();

            var species = Profile?.Species ?? HumanoidCharacterProfile.DefaultSpecies;
            var citizenships = _prototypeManager.EnumeratePrototypes<Content.Shared._Void.Passport.CitizenshipPrototype>()
                .Where(c => c.PlayerSelectable && c.AllowedSpecies.Contains(species))
                .OrderBy(c => c.Name)
                .ToList();

            var selectedIdx = 0;
            for (var i = 0; i < citizenships.Count; i++)
            {
                CitizenshipButton.AddItem(citizenships[i].Name, i);
                CitizenshipButton.SetItemMetadata(i, citizenships[i].ID);

                if (Profile?.Citizenship == citizenships[i].ID)
                    selectedIdx = i;
            }

            if (citizenships.Count > 0)
                CitizenshipButton.SelectId(selectedIdx);
        }

        private void RefreshBirthPlaces()
        {
            BirthPlaceButton.Clear();

            var citizenshipId = Profile?.Citizenship;
            if (string.IsNullOrEmpty(citizenshipId))
                return;

            if (!_prototypeManager.TryIndex<Content.Shared._Void.Passport.CitizenshipPrototype>(citizenshipId, out var proto))
                return;

            var selectedIdx = 0;
            for (var i = 0; i < proto.BirthPlaces.Count; i++)
            {
                BirthPlaceButton.AddItem(proto.BirthPlaces[i], i);
                BirthPlaceButton.SetItemMetadata(i, proto.BirthPlaces[i]);

                if (Profile?.BirthPlace == proto.BirthPlaces[i])
                    selectedIdx = i;
            }

            if (proto.BirthPlaces.Count > 0)
                BirthPlaceButton.SelectId(selectedIdx);
        }

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        private void UpdateNameEdit()
        {
            NameEdit.Text = Profile?.Name ?? "";
        }

        // Erida-Edit-Start
        private void UpdateFlavorTextEdit()
        {
            if (_flavorTextEdit != null)
            {
                _flavorTextEdit.TextRope = new Rope.Leaf(Profile?.FlavorText ?? "");
            }

            if (_flavorTextOOCEdit != null)
            {
                _flavorTextOOCEdit.TextRope = new Rope.Leaf(Profile?.OOCFlavorText ?? "");
            }

            if (_characterTextEdit != null)
            {
                _characterTextEdit.TextRope = new Rope.Leaf(Profile?.CharacterFlavorText ?? "");
            }

            if (_greenTextEdit != null)
            {
                _greenTextEdit.TextRope = new Rope.Leaf(Profile?.GreenFlavorText ?? "");
            }

            if (_yellowTextEdit != null)
            {
                _yellowTextEdit.TextRope = new Rope.Leaf(Profile?.YellowFlavorText ?? "");
            }

            if (_redTextEdit != null)
            {
                _redTextEdit.TextRope = new Rope.Leaf(Profile?.RedFlavorText ?? "");
            }

            if (_tagsTextEdit != null)
            {
                _tagsTextEdit.TextRope = new Rope.Leaf(Profile?.TagsFlavorText ?? "");
            }

            if (_linksTextEdit != null)
            {
                _linksTextEdit.TextRope = new Rope.Leaf(Profile?.LinksFlavorText ?? "");
            }

            if (_nsfwTextEdit != null)
            {
                _nsfwTextEdit.TextRope = new Rope.Leaf(Profile?.NSFWFlavorText ?? "");
            }
            // Erida start
            if (_flavorTextNSFWOOCEdit != null)
            {
                _flavorTextNSFWOOCEdit.TextRope = new Rope.Leaf(Profile?.NSFWOOCFlavorText ?? "");
            }
            if (_nsfwLinksTextEdit != null)
            {
                _nsfwLinksTextEdit.TextRope = new Rope.Leaf(Profile?.NSFWLinksFlavorText ?? "");
            }
            if (_nsfwTagsTextEdit != null)
            {
                _nsfwTagsTextEdit.TextRope = new Rope.Leaf(Profile?.NSFWTagsFlavorText ?? "");
            }
            // Erida end
        }
        // Erida-Edit-End

        private void UpdateAgeEdit()
        {
            AgeEdit.Text = Profile?.Age.ToString() ?? "";
        }

        // Erida start
        private void UpdateCustomSpeciesEdit()
        {
            IsCustomSpecies.Pressed = false;
            CustomSpeciesContainer.Visible = false;

            CustomSpeciesEdit.Text = Profile?.CustomSpecies ?? string.Empty;
            if (!string.IsNullOrEmpty(Profile?.CustomSpecies))
            {
                IsCustomSpecies.Pressed = true;
                CustomSpeciesContainer.Visible = true;
            }
        }
        // Erida end

        /// <summary>
        /// Updates selected job priorities to the profile's.
        /// </summary>
        private void UpdateJobPriorities()
        {
            foreach (var (jobId, prioritySelector) in _jobPriorities)
            {
                var priority = Profile?.JobPriorities.GetValueOrDefault(jobId, JobPriority.Never) ?? JobPriority.Never;
                prioritySelector.Select((int)priority);
            }
        }

        private void UpdateSexControls()
        {
            if (Profile == null)
                return;

            SexButton.Clear();

            var sexes = new List<Sex>();

            // add species sex options, default to just none if we are in bizzaro world and have no species
            if (_prototypeManager.Resolve<SpeciesPrototype>(Profile.Species, out var speciesProto))
            {
                foreach (var sex in speciesProto.Sexes)
                {
                    sexes.Add(sex);
                }
            }
            else
            {
                sexes.Add(Sex.Unsexed);
            }

            // add button for each sex
            foreach (var sex in sexes)
            {
                SexButton.AddItem(Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLower()}-text"), (int)sex);
            }

            if (sexes.Contains(Profile.Sex))
                SexButton.SelectId((int)Profile.Sex);
            else
                SexButton.SelectId((int)sexes[0]);
        }

        private void UpdateSkinColor()
        {
            if (Profile == null)
                return;

            var skin = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
            var strategy = _prototypeManager.Index(skin).Strategy;

            switch (strategy.InputType)
            {
                case SkinColorationStrategyInput.Unary:
                    {
                        if (!Skin.Visible)
                        {
                            Skin.Visible = true;
                            RgbSkinColorContainer.Visible = false;
                        }

                        Skin.Value = strategy.ToUnary(Profile.Appearance.SkinColor);

                        break;
                    }
                case SkinColorationStrategyInput.Color:
                    {
                        if (!RgbSkinColorContainer.Visible)
                        {
                            Skin.Visible = false;
                            RgbSkinColorContainer.Visible = true;
                        }

                        _rgbSkinColorSelector.Color = strategy.ClosestSkinColor(Profile.Appearance.SkinColor);

                        break;
                    }
            }
        }

        public void UpdateSpeciesGuidebookIcon()
        {
            SpeciesInfoButton.StyleClasses.Clear();

            var species = Profile?.Species;
            if (species is null)
                return;

            if (!_prototypeManager.Resolve<SpeciesPrototype>(species, out var speciesProto))
                return;

            // Don't display the info button if no guide entry is found
            if (!_prototypeManager.HasIndex<GuideEntryPrototype>(species))
                return;

            const string style = "SpeciesInfoDefault";
            SpeciesInfoButton.StyleIdentifier = style;
        }

        private void UpdateMarkings()
        {
            if (Profile == null)
            {
                return;
            }

            _markingsModel.OrganData = _markingManager.GetMarkingData(Profile.Species);
            _markingsModel.OrganProfileData = _markingManager.GetProfileData(Profile.Species, Profile.Sex, Profile.Appearance.SkinColor, Profile.Appearance.EyeColor);
            _markingsModel.Markings = Profile.Appearance.Markings;
        }

        private void UpdateGenderControls()
        {
            if (Profile == null)
            {
                return;
            }

            PronounsButton.SelectId((int)Profile.Gender);
        }

        private void UpdateSpawnPriorityControls()
        {
            if (Profile == null)
            {
                return;
            }

            SpawnPriorityButton.SelectId((int)Profile.SpawnPriority);
        }

        // begin Goobstation: port EE height/width sliders
        private void UpdateHeightWidthSliders()
        {
            if (Profile is null)
                return;

            var species = _species.Find(x => x.ID == Profile?.Species) ?? _species.First();

            // we increase the min/max values of the sliders before we set their value, just so that we don't accidentally clamp down on a value loaded from a profile when we shouldn't
            HeightSlider.MinValue = 0;
            HeightSlider.MaxValue = 2;
            HeightSlider.SetValueWithoutEvent(Profile?.Height ?? species.DefaultHeight);
            HeightSlider.MinValue = species.MinHeight;
            HeightSlider.MaxValue = species.MaxHeight;

            WidthSlider.MinValue = 0;
            WidthSlider.MaxValue = 2;
            WidthSlider.SetValueWithoutEvent(Profile?.Width ?? species.DefaultWidth);
            WidthSlider.MinValue = species.MinWidth;
            WidthSlider.MaxValue = species.MaxWidth;

            var height = MathF.Round(species.AverageHeight * HeightSlider.Value);
            HeightLabel.Text = Loc.GetString("humanoid-profile-editor-height-label", ("height", (int)height));

            var width = MathF.Round(species.AverageWidth * WidthSlider.Value);
            WidthLabel.Text = Loc.GetString("humanoid-profile-editor-width-label", ("width", (int)width));

            UpdateDimensions(SliderUpdate.Both);
        }

        private enum SliderUpdate
        {
            Height,
            Width,
            Both
        }

        private void UpdateDimensions(SliderUpdate updateType)
        {
            if (Profile == null)
                return;

            var species = _species.Find(x => x.ID == Profile?.Species) ?? _species.First();

            var heightValue = Math.Clamp(HeightSlider.Value, species.MinHeight, species.MaxHeight);
            var widthValue = Math.Clamp(WidthSlider.Value, species.MinWidth, species.MaxWidth);
            var sizeRatio = species.SizeRatio;
            var ratio = heightValue / widthValue;

            if (updateType == SliderUpdate.Height || updateType == SliderUpdate.Both)
                if (ratio < 1 / sizeRatio || ratio > sizeRatio)
                    widthValue = heightValue / (ratio < 1 / sizeRatio ? (1 / sizeRatio) : sizeRatio);

            if (updateType == SliderUpdate.Width || updateType == SliderUpdate.Both)
                if (ratio < 1 / sizeRatio || ratio > sizeRatio)
                    heightValue = widthValue * (ratio < 1 / sizeRatio ? (1 / sizeRatio) : sizeRatio);

            heightValue = Math.Clamp(heightValue, species.MinHeight, species.MaxHeight);
            widthValue = Math.Clamp(widthValue, species.MinWidth, species.MaxWidth);

            HeightSlider.SetValueWithoutEvent(heightValue);
            WidthSlider.SetValueWithoutEvent(widthValue);

            SetProfileHeight(heightValue);
            SetProfileWidth(widthValue);

            var height = MathF.Round(species.AverageHeight * HeightSlider.Value);
            HeightLabel.Text = Loc.GetString("humanoid-profile-editor-height-label", ("height", (int)height));

            var width = MathF.Round(species.AverageWidth * WidthSlider.Value);
            WidthLabel.Text = Loc.GetString("humanoid-profile-editor-width-label", ("width", (int)width));

            UpdateWeight();
        }

        private void UpdateWeight()
        {
            if (Profile == null)
                return;

            var species = _species.Find(x => x.ID == Profile.Species) ?? _species.First();
            //  TODO: Remove obsolete method
            _prototypeManager.Index(species.Prototype).TryGetComponent<FixturesComponent>(out var fixture, _entManager.ComponentFactory);

            if (fixture != null)
            {
                var avg = (Profile.Width + Profile.Height) / 2;
                var weight = FixtureSystem.GetMassData(fixture.Fixtures["fix1"].Shape, fixture.Fixtures["fix1"].Density).Mass * avg;
                WeightLabel.Text = Loc.GetString("humanoid-profile-editor-weight-label", ("weight", (int)weight));
            }
            else // Whelp, the fixture doesn't exist, guesstimate it instead
                WeightLabel.Text = Loc.GetString("humanoid-profile-editor-weight-label", ("weight", (int)71));

            if (SpriteView.Sprite != null)
                _sharedScaleVisualsSystem.SetSpriteScale(SpriteView.PreviewDummy, new Vector2(Profile.Width, Profile.Height));
        }
        // end Goobstation: port EE height/width sliders

        private void UpdateEyePickers()
        {
            if (Profile == null)
            {
                return;
            }

            _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor);
            EyeColorPicker.SetData(Profile.Appearance.EyeColor);
        }

        private void UpdateSaveButton()
        {
            SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction)((int)direction % 4 * 2);
        }

        private void RandomizeEverything()
        {
            Profile = HumanoidCharacterProfile.Random();
            SetProfile(Profile, CharacterSlot);
            SetDirty();
        }

        private void RandomizeName()
        {
            if (Profile == null) return;
            var name = HumanoidCharacterProfile.GetName(Profile.Species, Profile.Gender);
            SetName(name);
            UpdateNameEdit();
        }

        private async void ExportImage()
        {
            if (_imaging)
                return;

            var dir = SpriteView.OverrideDirection ?? Direction.South;

            // I tried disabling the button but it looks sorta goofy as it only takes a frame or two to save
            _imaging = true;
            await _entManager.System<ContentSpriteSystem>().Export(SpriteView.PreviewDummy, dir, includeId: false);
            _imaging = false;
        }

        private async void ImportProfile()
        {
            if (_exporting || CharacterSlot == null || Profile == null)
                return;

            StartExport();
            await using var file = await _dialogManager.OpenFile(new FileDialogFilters(new FileDialogFilters.Group("yml")), FileAccess.Read);

            if (file == null)
            {
                EndExport();
                return;
            }

            try
            {
                var profile = HumanoidCharacterProfile.FromStream(file, _playerManager.LocalSession!);
                var oldProfile = Profile;
                SetProfile(profile, CharacterSlot);

                IsDirty = !profile.MemberwiseEquals(oldProfile);
            }
            catch (Exception exc)
            {
                _sawmill.Error($"Error when importing profile\n{exc.StackTrace}");
            }
            finally
            {
                EndExport();
            }
        }

        private async void ExportProfile()
        {
            if (Profile == null || _exporting)
                return;

            StartExport();
            var file = await _dialogManager.SaveFile(new FileDialogFilters(new FileDialogFilters.Group("yml")));

            if (file == null)
            {
                EndExport();
                return;
            }

            try
            {
                var dataNode = Profile.ToDataNode();
                await using var writer = new StreamWriter(file.Value.fileStream);
                dataNode.Write(writer);
            }
            catch (Exception exc)
            {
                _sawmill.Error($"Error when exporting profile\n{exc.StackTrace}");
            }
            finally
            {
                EndExport();
                await file.Value.fileStream.DisposeAsync();
            }
        }

        private void StartExport()
        {
            _exporting = true;
            ImportButton.Disabled = true;
            ExportButton.Disabled = true;
        }

        private void EndExport()
        {
            _exporting = false;
            ImportButton.Disabled = false;
            ExportButton.Disabled = false;
        }
    }
}
