using Content.Shared._Void.Passport;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using static Content.Shared._Void.Passport.PassportComponent;

namespace Content.Client._Void.Passport.UI;

[GenerateTypedNameReferences]
public sealed partial class PassportWindow : DefaultWindow
{
    public PassportWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(PassportBoundUserInterfaceState state)
    {
        var fullName = $"{state.OwnerName ?? "?"} {state.OwnerSurname ?? "?"}";
        NameLabel.Text = fullName;

        var age = PassportComponent.CurrentYear - state.BirthYear;
        AgeLabel.Text = age.ToString();
        HeightLabel.Text = $"{state.Height:F1} cm";
        WeightLabel.Text = $"{state.Weight:F1} kg";
        CitizenshipLabel.Text = state.Citizenship ?? "?";
        BirthPlaceLabel.Text = state.BirthPlace ?? "?";

        var entMan = IoCManager.Resolve<IEntityManager>();
        if (entMan.TryGetEntity(state.PhotoEntity, out var photoEntity))
            PhotoView.SetEntity(photoEntity.Value);
    }
}
